[[definition]]
text = "without charge, free"
class = "adverb"
example = "Ce srvis wuz ixwd greytis."

[[definition]]
text = "without charge, free"
class = "adjective"
example = "Ce greytis srvis wuz ixwd."