[[definition]]
text = "without charge, free"
class = "adverb"
example = "Cu srvis wuz ixwd greytis."

[[definition]]
text = "without charge, free"
class = "adjective"
example = "Cu greytis srvis wuz ixwd."