[[definition]]
text = "actually existing as a thing; not imagined or fictional"
class = "adjective"
example = "Cis iz suw ryl ond trw."

[[definition]]
text = "Lorem ipsum dolor sit amet"
class = "exclamation"
example = "Ryl!"